# Publish all joint states -----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Effort Controllers ---------------------------------------
glove_R_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: glove_R_joint
  pid: {p: 10000.0, i: 0.0, d: 100.0}
glove_L_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: glove_L_joint
  pid: {p: 10000.0, i: 0.0, d: 100.0}

# We need to have Fake controllers for all the non fixed joints to have their states

neck_1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: neck_1_joint
  pid: {p: 0.0, i: 0.0, d: 0.0}
neck_2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: neck_2_joint
  pid: {p: 0.0, i: 0.0, d: 0.0}
neck_3_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: neck_3_joint
  pid: {p: 0.0, i: 0.0, d: 0.0}
neck_4_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: neck_4_joint
  pid: {p: 0.0, i: 0.0, d: 0.0}
neck_5_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: neck_5_joint
  pid: {p: 0.0, i: 0.0, d: 0.0}

    